# http://wiki.ros.org/navigation/Tutorials/RobotSetup#Base_Local_Planner_Configuration
TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.05
  max_vel_y: 0.25
  min_vel_y: 0.05
  max_rotational_vel: 0.25
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: true
