## Reference http://wiki.ros.org/navigation/Tutorials/RobotSetup#Costmap_Configuration_.28local_costmap.29_.26_.28global_costmap.29
## Copied from https://github.com/turtlebot/turtlebot_apps/blob/75bc684ff879e8cfe0bc9295d18c2c56859d4e25/turtlebot_navigation/laser/costmap_common_params.yaml
# The "obstacle_range" parameter determines the maximum range sensor reading that will result in an obstacle being put into the costmap. Here, we have it set at 2.5 meters, which means that the robot will only update its map with information about obstacles that are within 2.5 meters of the base. 
obstacle_range: 2.5

# The "raytrace_range" parameter determines the range to which we will raytrace freespace given a sensor reading. Setting it to 3.0 meters as we have above means that the robot will attempt to clear out space in front of it up to 3.0 meters away given a sensor reading. 
raytrace_range: 1.5

# In the case of specifying the footprint, the center of the robot is assumed to be at (0.0, 0.0) and both clockwise and counterclockwise specifications are supported. 
footprint: [[-1.5, 1.5], [1.5, 1.5], [1.5, -1.5], [-1.5, -1.5]]

# The inflation radius should be set to the maximum distance from obstacles at which a cost should be incurred. For example, setting the inflation radius at 0.55 meters means that the robot will treat all paths that stay 0.55 meters or more away from obstacles as having equal obstacle cost. 
inflation_radius: 0.50

observation_sources: scan 
scan: {sensor_frame: /hokuyo_sensor_link, data_type: LaserScan, topic: /spur/laser/scan, marking: true, clearing: true}

