map_update_interval: 1.0

maxUrange:  8.0
maxRange :  6.0

sigma     : 0.05
kernelSize: 1
lstep     : 0.05
astep     : 0.05
iterations: 10
lsigma    : 0.075
ogain     : 3.0
lskip     : 0

minimumScore : 100

srr: 0.01
srt: 0.02
str: 0.01
stt: 0.02

linearUpdate     :  0.5
angularUpdate    :  0.436
temporalUpdate   : -1.0
resampleThreshold:  0.5
particles        : 30

xmin : -1.0
ymin : -1.0
xmax :  1.0
ymax :  1.0
delta:    0.02

llsamplerange: 0.01
llsamplestep : 0.01
lasamplerange: 0.005
lasamplestep : 0.005

transform_publish_period: 0.05
