scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 20
    max_angle: 160
    neighbors: 10
    window: 1
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.5
    upper_threshold: 9   # see spur.gzebo.xacro gazebo/sensor/ray/range/max
